EconomyProvider: 'Vault'

CostToRemove: 100

# If you are using PEconomy please specify which wallet you would like to use
WalletName: "tokens"

GUI:
  - 'FFFF1FFFF'
  - 'ggggggggg'
  - 'ggggggggg'
  - 'ggggggggg'
  - 'FFFFFFFFF'

messages:
  NotEnoughXP: 'You do not have enough XP to disenchant this'