EconomyProvider: 'Vault'

CostToRemove: 100

GUI:
  - 'FFFF1FFFF'
  - 'ggggggggg'
  - 'ggggggggg'
  - 'ggggggggg'
  - 'FFFFFFFFF'

messages:
  NotEnoughXP: 'You do not have enough XP to disenchant this'