name: DisEnchant
version: '${project.version}'
main: me.rebelmythik.disenchant.DisEnchant
api-version: 1.18
softDepends: [ Vault, PEconomy]

commands:
  disenchant:
    description: 'Disenchants'
permissions:
  disenchant.reload:
    description: 'Lets you reload plugin'
  disenchant.use:
    description: 'Lets player use disenchant menu'